# Generated by Django 5.2.4 on 2025-07-14 23:29

import django.db.models.deletion
import sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, unique=True, validators=[sms.models.validate_numero])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenu', models.TextField(max_length=480)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('EN ATTENTE', 'En attente'), ('ENVOYÉ', 'Envoyé'), ('ERREUR', 'Erreur'), ('DELIVRÉ', 'Délivré')], default='EN ATTENTE', max_length=50)),
                ('erreur', models.CharField(blank=True, max_length=10, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_dlr', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_deliveries', to='sms.client')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sms.sms')),
            ],
        ),
    ]
